package `in`.iot.lab.iotlights.data.model

/**
 * This is the structure of the Light Data which will be inside each [LightResponseData]
 *
 * @param id This is the Id generated by the Database
 * @param date_created This is the date when the Data was entries in the Database
 * @param date_updated This is the date when the Data was updated in the Database
 * @param request This is the light Status of the Lab
 */
data class LightData(
    val id: Int,
    val date_created: String,
    val date_updated: String,
    val request: Int
)
